export const cardList = [ 
    {
      "country": "russ",
      "director": "russ",
       "duration": 230,
      "year": "russ",
      "description": "russ",
      "image": "https://sun9-7.userapi.com/impg/Kz4hvVWX7GQp9cwpVq8o2vIFS4xpyJkyPVY6bQ/Z2U0F8md_f8.jpg?size=800x1020&quality=95&sign=f2146c4c136d62f903b2c15d62322483&type=album",
      "trailerLink": "russ",
      "thumbnail": "russ",
      "owner": [
        "russ",
        "12"
      ],
      "movieId": "1",
      "nameRU": "russ",
      "nameEN": "russ",
    },
    {
      "country": "russ",
      "director": "russ",
        "duration": 265,
      "year": "russ",
      "description": "russ",
      "image": "https://sun9-72.userapi.com/impg/CP6Ikwx1c67kbIcNo6EtPEakqwmQ2kqOX4-Y_A/lHqfoTJ2pQs.jpg?size=1016x1080&quality=95&sign=19ea8e95f39cae2c0aa696563faaa186&type=album",
      "trailerLink": "russ",
      "thumbnail": "russ",
      "owner": [
        "russ",
        "12"
      ],
      "movieId": "2",
      "nameRU": "russ",
      "nameEN": "russ",
    },
    {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "11",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "3",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-72.userapi.com/impg/CP6Ikwx1c67kbIcNo6EtPEakqwmQ2kqOX4-Y_A/lHqfoTJ2pQs.jpg?size=1016x1080&quality=95&sign=19ea8e95f39cae2c0aa696563faaa186&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "12",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-7.userapi.com/impg/Kz4hvVWX7GQp9cwpVq8o2vIFS4xpyJkyPVY6bQ/Z2U0F8md_f8.jpg?size=800x1020&quality=95&sign=f2146c4c136d62f903b2c15d62322483&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "4",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-60.userapi.com/impg/Y8VdMgqduFk-yxhIRw-dj_laFmeKxBjBXo2uwQ/YBhEhoZwY-0.jpg?size=1280x889&quality=95&sign=4f43e466089e51c3f879fc20ac088dc8&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "31",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-60.userapi.com/impg/Y8VdMgqduFk-yxhIRw-dj_laFmeKxBjBXo2uwQ/YBhEhoZwY-0.jpg?size=1280x889&quality=95&sign=4f43e466089e51c3f879fc20ac088dc8&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "5",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "13",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "6",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-60.userapi.com/impg/Y8VdMgqduFk-yxhIRw-dj_laFmeKxBjBXo2uwQ/YBhEhoZwY-0.jpg?size=1280x889&quality=95&sign=4f43e466089e51c3f879fc20ac088dc8&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "14",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "7",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-72.userapi.com/impg/CP6Ikwx1c67kbIcNo6EtPEakqwmQ2kqOX4-Y_A/lHqfoTJ2pQs.jpg?size=1016x1080&quality=95&sign=19ea8e95f39cae2c0aa696563faaa186&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "197",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "8",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-60.userapi.com/impg/Y8VdMgqduFk-yxhIRw-dj_laFmeKxBjBXo2uwQ/YBhEhoZwY-0.jpg?size=1280x889&quality=95&sign=4f43e466089e51c3f879fc20ac088dc8&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "15",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-58.userapi.com/impg/U56dB_PXsvZ84AgSqUTgYCk8eZmqsbro60djpg/zEF-nZMlV7s.jpg?size=664x1000&quality=95&sign=fc62dbdee34a3d4e9f37f566b482a7bd&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "9",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "16",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "20",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-58.userapi.com/impg/U56dB_PXsvZ84AgSqUTgYCk8eZmqsbro60djpg/zEF-nZMlV7s.jpg?size=664x1000&quality=95&sign=fc62dbdee34a3d4e9f37f566b482a7bd&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "181",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "21",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "182",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-58.userapi.com/impg/U56dB_PXsvZ84AgSqUTgYCk8eZmqsbro60djpg/zEF-nZMlV7s.jpg?size=664x1000&quality=95&sign=fc62dbdee34a3d4e9f37f566b482a7bd&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "22",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "183",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "23",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-58.userapi.com/impg/U56dB_PXsvZ84AgSqUTgYCk8eZmqsbro60djpg/zEF-nZMlV7s.jpg?size=664x1000&quality=95&sign=fc62dbdee34a3d4e9f37f566b482a7bd&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "143",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "24",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "145",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "25",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "146",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "26",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
         "duration": 230,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "147",
        "nameRU": "russ",
        "nameEN": "russ",
      },
      {
        "country": "russ",
        "director": "russ",
          "duration": 265,
        "year": "russ",
        "description": "russ",
        "image": "https://sun9-44.userapi.com/impg/poddyDrvBJ39m20mYf-xB4pkHs8fSUqBQc0GYw/pIEqFaNi1a0.jpg?size=1280x741&quality=95&sign=4fb3d3c4b5589ebc935856230d1ebdc0&type=album",
        "trailerLink": "russ",
        "thumbnail": "russ",
        "owner": [
          "russ",
          "12"
        ],
        "movieId": "27",
        "nameRU": "russ",
        "nameEN": "russ",
      },
  ]